# Generated by Django 5.0.6 on 2024-05-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='foto_perfil/', verbose_name='foto de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'informação extra',
                'verbose_name_plural': 'informações extras',
            },
        ),
    ]
